name: econark
channels:
  - conda-forge
dependencies:
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - econ-ark=0.15.1
  - ipywidgets=8.1.5
  - jupyter-server-proxy=4.4.0
  - jupyterlab=4.2.5
  - jupyterlab-myst=2.4.2
  - linearmodels=6.1
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mystmd=1.3.16
  - openssl=3.3.2
  - pandas=2.2.3
  - pandas-datareader=0.10.0
  - python=3.11.10
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - statsmodels=0.14.4
  - sympy=1.13.3
  - tqdm=4.66.6
  - watchdog=6.0.0
prefix: /home/idies/mambaforge/envs/econark
